credits = "<p align='right'><sub>Powered by https://doteki.org</sub></p>"

[sections.blog]
plugin = "feed"
url = "https://w3teal.bearblog.dev/feed/"
n = 7
show_date = true
date_format = "%B %d, %Y | %H:%M"
append_text = "\n\nMore on [w3teal.bearblog.dev](https://w3teal.bearblog.dev/posts/)"

[sections.last_updated]
plugin = "current_date"
format = "%B %d, %Y | %H:%M"
append_text = "."
