[sections.blog]
plugin = "feed"
url = "https://w3teal.bearblog.dev/feed/"
n = 7
show_date = true
append_text = "\n\nMore on [w3teal.bearblog.dev](https://w3teal.bearblog.dev/posts/)"

[sections.last_updated]
plugin = "current_date"
format = "%F %d%S, %Y"
append_text = "."
